name: ads_project

services:
  arcade:
    image: arcadedata/arcadedb:latest
    platform: linux/amd64
    ports:
      - "2480:2480"
      - "2424:2424"
    volumes:
      - ./data:/home/arcadedb/data
      - ./scripts:/home/arcadedb/scripts
      - ./config:/tmp/config
    environment:
      JAVA_OPTS: "-Darcadedb.server.rootPassword=rootroot"
    post_start:
      - command: >
          /bin/bash -c "apt-get -y update &&
                        apt-get -y install curl &&
                        apt-get -y install python3 &&
                        apt-get -y install python3-pip &&
                        cd /tmp/config &&
                        pip3 install -r ./requirements.txt --break-system-packages &&
                        chmod 777 -R /home/arcadedb/ && 
                        echo koniec"
        user: root